{
 "title": "Expunji",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Outcomes",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(dns_queries_total{outcome=\"abandoned\"}[5m])) OR vector(0)",
     "legendFormat": "Abandoned"
    },
    {
     "expr": "sum(sum_over_time(dns_queries_total{outcome=~\"allowed.*\"}[5m])) OR vector(0)",
     "legendFormat": "Allowed"
    },
    {
     "expr": "sum(sum_over_time(dns_queries_total{outcome=\"bad_packet\"}[5m])) OR vector(0)",
     "legendFormat": "Bad Packet"
    },
    {
     "expr": "sum(sum_over_time(dns_queries_total{outcome=\"blocked\"}[5m])) OR vector(0)",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Query Outcomes per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(dns_queries_total{outcome=\"abandoned\"}[5m])) * 60 OR vector(0)",
     "legendFormat": "Abandoned"
    },
    {
     "expr": "sum(rate(dns_queries_total{outcome=~\"allowed.*\"}[5m])) * 60 OR vector(0)",
     "legendFormat": "Allowed"
    },
    {
     "expr": "sum(rate(dns_queries_total{outcome=\"bad_packet\"}[5m])) * 60 OR vector(0)",
     "legendFormat": "Bad Packet"
    },
    {
     "expr": "sum(rate(dns_queries_total{outcome=\"blocked\"}[5m])) * 60 OR vector(0)",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Total Queries per minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dns_queries_total[5m])) * 60 OR vector(0)"
    }
   ]
  },
  {
   "title": "Abandoned Queries per minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dns_queries_total{outcome=\"abandoned\"}[5m])) * 60 OR vector(0)"
    }
   ]
  },
  {
   "title": "Allowed Queries per minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dns_queries_total{outcome=~\"allowed.*\"}[5m])) * 60 OR vector(0)"
    }
   ]
  },
  {
   "title": "Bad Packet Queries per minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dns_queries_total{outcome=\"bad_packet\"}[5m])) * 60 OR vector(0)"
    }
   ]
  },
  {
   "title": "Blocked Queries per minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dns_queries_total{outcome=\"blocked\"}[5m])) * 60 OR vector(0)"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(dns_queries_total{outcome=\"allowed_cache\"}[5m])) OR vector(0)",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(sum_over_time(dns_queries_total{outcome=\"allowed_no_cache\"}[5m])) OR vector(0)",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Hosts Table Rows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hosts_table_rows" }
   ]
  }
 ]
}